### ISSUE TITLE
module 'lxp.lom' not found

### ISSUE THREAD

**Issue by muava12** [bkersten/lua-xpath#1]
get this error on executing, how to fix that??

stdin:1: module 'lxp.lom' not found:
    no field package.preload['lxp.lom']
    no file '/usr/local/share/lua/5.2/lxp/lom.lua'
    no file '/usr/local/share/lua/5.2/lxp/lom/init.lua'
    no file '/usr/local/lib/lua/5.2/lxp/lom.lua'
    no file '/usr/local/lib/lua/5.2/lxp/lom/init.lua'
    no file '/usr/share/lua/5.2/lxp/lom.lua'
    no file '/usr/share/lua/5.2/lxp/lom/init.lua'
    no file './lxp/lom.lua'
    no file '/usr/local/lib/lua/5.2/lxp/lom.so'
    no file '/usr/lib/i386-linux-gnu/lua/5.2/lxp/lom.so'
    no file '/usr/lib/lua/5.2/lxp/lom.so'
    no file '/usr/local/lib/lua/5.2/loadall.so'
    no file './lxp/lom.so'
    no file '/usr/local/lib/lua/5.2/lxp.so'
    no file '/usr/lib/i386-linux-gnu/lua/5.2/lxp.so'
    no file '/usr/lib/lua/5.2/lxp.so'
    no file '/usr/local/lib/lua/5.2/loadall.so'
    no file './lxp.so'
stack traceback:
    [C]: in function 'require'
    stdin:1: in main chunk
    [C]: in ?

**Comment by bkersten** [comment]
Hi Muafa,

Lua Object Model from LuaExpat is required. See https://matthewwild.co.uk/projects/luaexpat/ for download options.
